server:
  port: 8000

spring:
  datasource:
    username: root
    password: yunhao802351
    url: jdbc:mysql://175.178.111.96:3306/gulimall_ums
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.111.96:8848
  application:
    name: shoppmall-member
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto