server:
  port: 7000

spring:
  datasource:
    username: root
    password: yunhao802351
    url: jdbc:mysql://175.178.111.96:3306/gulimall_sms
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
